
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 18 12:14:08 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREAT_EQU = 30;
  public static final int CONST = 20;
  public static final int CHAR = 16;
  public static final int NOTEQUAL = 31;
  public static final int LPAREN = 6;
  public static final int GREATER = 29;
  public static final int SEMI = 5;
  public static final int CONTINUE = 26;
  public static final int MINUS = 38;
  public static final int LESS = 28;
  public static final int FOR = 24;
  public static final int RPAREN = 7;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int BOOL = 15;
  public static final int COMMA = 8;
  public static final int INC = 35;
  public static final int DIV = 40;
  public static final int PLUS = 11;
  public static final int IF = 18;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int MOD = 41;
  public static final int NUMBER = 14;
  public static final int EQUCMP = 32;
  public static final int LSQBRACKET = 22;
  public static final int BREAK = 25;
  public static final int IDENT = 17;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int READ = 37;
  public static final int ENUM = 21;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int RSQBRACKET = 23;
  public static final int CNT = 44;
  public static final int DEC = 36;
  public static final int LESS_EQU = 27;
  public static final int PRINT = 9;
}

